apiVersion: apps/v1
kind: Deployment
metadata:
  name: ronin-frontend
  namespace: ronin-namespace
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: ronin-frontend
  template:
    metadata:
      labels:
        app: ronin-frontend
    spec:
      containers:
        - name: ronin-frontend
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
          readinessProbe:
            httpGet:
              path: /
              port: {{ .Values.service.port }}
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 3
          resources:
            requests:
              cpu: 100m
              memory: 64Mi
            limits:
              cpu: 250m
              memory: 128Mi

