apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-app-ronin-frontend
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/GeorgeZudikhin/ronin-infra
    targetRevision: main
    path: k8s/charts/ronin-frontend
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: ronin-namespace
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
