apiVersion: apps/v1
kind: Deployment
metadata:
  name: ronin-db
  namespace: ronin-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ronin-db
  template:
    metadata:
      labels:
        app: ronin-db
    spec:
      containers:
        - name: ronin-db
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
          env:
            - name: POSTGRES_DB
              value: {{ .Values.postgres.db }}
            - name: POSTGRES_USER
              value: {{ .Values.postgres.user }}
            - name: POSTGRES_PASSWORD
              value: {{ .Values.postgres.password }}
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: postgres-pvc
