apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv
  namespace: ronin-namespace
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: "{{ .Values.persistence.size }}"
  storageClassName: standard
  hostPath:
    path: /postgres
