apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: ronin-namespace
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  volumeName: postgres-pv
  resources:
    requests:
      storage: "{{ .Values.persistence.size }}"
