apiVersion: v1
kind: Service
metadata:
  name: ronin-db
  namespace: ronin-namespace
spec:
  selector:
    app: ronin-db
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
