apiVersion: v1
kind: ConfigMap
metadata:
  name: ronin-config
  namespace: ronin-namespace
data:
  DATABASE_HOST: "postgres-service"
  DATABASE_PORT: "5432"
  BACKEND_HOST: "backend-service"
  BACKEND_PORT: "8080"
