apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ronin-ingress
  namespace: ronin-namespace
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: ronin.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ronin-frontend-service
                port:
                  number: 80
