apiVersion: apps/v1
kind: Deployment
metadata:
  name: ronin-backend
  namespace: ronin-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ronin-backend
  template:
    metadata:
      labels:
        app: ronin-backend
    spec:
      containers:
        - name: ronin-backend
          image: yehorzudikhin/ronin-backend:latest
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: docker
          imagePullPolicy: Always
