apiVersion: apps/v1
kind: Deployment
metadata:
  name: ronin-frontend
  namespace: ronin-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ronin-frontend
  template:
    metadata:
      labels:
        app: ronin-frontend
    spec:
      containers:
        - name: ronin-frontend
          image: yehorzudikhin/ronin-frontend:hope
          ports:
            - containerPort: 80
          imagePullPolicy: Always
